name: CI Pipeline
on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Set-up-JDK:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
  Build:
    runs-on: ubuntu-latest
    needs: Set-up-JDK
    steps:
      - uses: actions/checkout@v2
      - name: Building project
        working-directory: ./JHotDraw
        run: mvn --batch-mode --update-snapshots verify
        
  Test:
    runs-on: ubuntu-latest
    needs: [Set-up-JDK, Build]
    steps:
      - uses: actions/checkout@v2
      - name: Testing project
        working-directory: ./JHotDraw
        run: mvn test 